[package]
name = "terminal-fireworks"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.28.1"
enum-map = "2.7.3"
glam = "0.29.0"
rand = "0.8.5"
